spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${news_rds_username}
    password: ${news_rds_password}
    url: ${news_rds_url}
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always