spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
    url: jdbc:mysql://localhost:3306/wenews?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul