spring:
  config:
    import:
      - application-db.yml
      - application-flyway.yml
      - application-jpa.yml
      - application-oauth.yml
  mvc:
    #swagger
    pathmatch:
      matching-strategy: ant_path_matcher

# mustache korean encoding
server:
  servlet:
    encoding:
      force-response: true




