#
server:
  port: 9991


spring:
  mvc:
    #swagger
    pathmatch:
      matching-strategy: ant_path_matcher
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wenews_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  #flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/wenews_test?serverTimezone=UTC&characterEncoding=UTF-8
    user: root
    password: qwer1234


