spring:
  config:
    import:
      - application-db.yml
      - application-flyway.yml
      - application-jpa.yml
      - application-oauth.yml
  mvc:
    #swagger
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# mustache korean encoding
server:
  servlet:
    encoding:
      force-response: true
  port: 9999


# path
path:
  storage-path: "http://localhost:9999"
  connect-path: "/imagePath/"
  file-path: "C:/News/"
  

#  file-path: "/C/news/"
#  connect-path: "/imagePath/**"
#    load-path: "file:///home/uploadedImage"




