FROM azul/zulu-openjdk:11-latest

EXPOSE 8080
ARG JAR_FILE=wenews-0.0.1-SNAPSHOT.jar
COPY /var/lib/jenkins/workspace/news/server/build/libs/${JAR_FILE} ${JAR_FILE}
ENTRYPOINT ["java", "-jar", "/wenews-0.0.1-SNAPSHOT.jar"]


